// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9fJYuwBx56kioimvsCQA8yZ6TKugzQBw',
    appId: '1:91193218059:web:d66dde4811cad55ebaa30e',
    messagingSenderId: '91193218059',
    projectId: 'emplbeemobile',
    authDomain: 'emplbeemobile.firebaseapp.com',
    storageBucket: 'emplbeemobile.firebasestorage.app',
    measurementId: 'G-FZ1JXPB0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL_xDJrBWhYwUh65g2NbMDO465dkMdvoM',
    appId: '1:91193218059:android:d9ab0e23e85f11adbaa30e',
    messagingSenderId: '91193218059',
    projectId: 'emplbeemobile',
    storageBucket: 'emplbeemobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTMX55Sb5nvd9sv8cYCW8aay6gUBWzbs',
    appId: '1:91193218059:ios:b0b0ce688bad31a9baa30e',
    messagingSenderId: '91193218059',
    projectId: 'emplbeemobile',
    storageBucket: 'emplbeemobile.firebasestorage.app',
    iosBundleId: 'com.example.emplbeeMob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTMX55Sb5nvd9sv8cYCW8aay6gUBWzbs',
    appId: '1:91193218059:ios:b0b0ce688bad31a9baa30e',
    messagingSenderId: '91193218059',
    projectId: 'emplbeemobile',
    storageBucket: 'emplbeemobile.firebasestorage.app',
    iosBundleId: 'com.example.emplbeeMob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9fJYuwBx56kioimvsCQA8yZ6TKugzQBw',
    appId: '1:91193218059:web:4366df0253b784e0baa30e',
    messagingSenderId: '91193218059',
    projectId: 'emplbeemobile',
    authDomain: 'emplbeemobile.firebaseapp.com',
    storageBucket: 'emplbeemobile.firebasestorage.app',
    measurementId: 'G-R0KCTLMPXD',
  );
}
